#!/bin/bash
COLOR="$(tput setaf 11)"
BOLD="$(tput bold)"
RESET="$(tput sgr0)"

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
echo "${COLOR}Running diversitest from directory ${BOLD}${SCRIPT_DIR}${RESET}"

BUILD_DIR="$(mktemp -d)"
echo "${COLOR}Created a temporary directory ${BOLD}${BUILD_DIR}${RESET}"

echo "${COLOR}Setting permissions for the temporary directory${RESET}"
chmod a+rsx $BUILD_DIR

echo "${COLOR}Copying from local directory${RESET}"
cp -R . $BUILD_DIR

echo "${COLOR}Changing dir to ${BOLD}${BUILD_DIR}${RESET}"
cd $BUILD_DIR

echo "${COLOR}Running tests${RESET}"
php $SCRIPT_DIR/diversitest.php

echo "${COLOR}Cleaning up temporary dir ${BOLD}${BUILD_DIR}${RESET}"
rm -rf $BUILD_DIR

echo "${COLOR}Done${RESET}"
